name: tzolkin
description: A simple calendar element.
version: 2.1.4
author: John Ryan <john.p.ryan4@gmail.com>
homepage: https://github.com/apptreesoftware/tzolkin

environment:
  sdk: ">=1.8.0 <2.0.0"

dependencies:
  polymer: ^1.0.0-rc.17
  polymer_elements: ^1.0.0-rc.9
  web_components: ^0.12.5
  browser: ^0.10.0+2
  date_utils: ^0.0.2

dev_dependencies:
  test: '>=0.12.0 <0.13.0'

transformers:
- polymer:
    entry_points:
      - example/index.html
